# -*- coding: utf-8 -*-
"""Another copy of DHV Dream.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_1Tfk-vOePMCYzhBNpCYtL6ZHihlQ_D2
"""

!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118  # For CUDA 11.8 (Colab default)
!pip install timm albumentations scikit-learn matplotlib seaborn tqdm opencv-python

!pip uninstall focal-loss-torch -y  # Clean if partial
!pip install focal-loss-torch
print("FocalLoss reinstalled—uses class_num=7 for multi-class.")



from google.colab import drive
drive.mount('/content/drive')

# Create output directory in Drive
import os
os.makedirs('/content/drive/MyDrive/dermamnist/phase2/models', exist_ok=True)
os.makedirs('/content/drive/MyDrive/dermamnist/phase2/logs', exist_ok=True)
os.makedirs('/content/drive/MyDrive/dermamnist/phase2/plots', exist_ok=True)

# Paths (adjust if needed)
DATA_PATH = '/content/drive/MyDrive/final_dermamnist_224.npz'
METADATA_PATH = '/content/drive/MyDrive/final_metadata.json'
OUTPUT_DIR = '/content/drive/MyDrive/dermamnist/phase2'

print("Setup complete. Ensure data files are in /MyDrive/dermamnist/")

"""2nd"""

import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader, WeightedRandomSampler
from torch.cuda.amp import autocast, GradScaler
import timm
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter
import json
import os
from tqdm import tqdm
import random
from PIL import Image
import albumentations as A
from albumentations.pytorch import ToTensorV2
from sklearn.utils import resample  # For bootstrap
import copy

# Set seeds for reproducibility
def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

set_seed(42)

# Test 1: Full Dataset for Rare Exposure (+2-4% val/F1; Batch=32 default, loaders to 16)
BATCH_SIZE = 32  # Default; Cell 3 adjusts to 16 for full to avoid OOM
NUM_WORKERS = 2
NUM_EPOCHS_STAGE_A = 15
NUM_EPOCHS_STAGE_B = 25
LEARNING_RATE_A = 4e-3  # Mid for 77% A
LEARNING_RATE_B = 5e-5  # Conservative B
WEIGHT_DECAY = 3e-4
PATIENCE = 7
SUBSET_FRACTION = 1.0  # Test 1: Full (from 0.5; ~2x rares, +2-4%)
LABEL_SMOOTHING = 0.07  # Mild for CE

# ImageNet Norm
IMAGENET_MEAN = np.array([0.485, 0.456, 0.406])
IMAGENET_STD = np.array([0.229, 0.224, 0.225])

# Paths (from .py)
DATAPATH = '/content/drive/MyDrive/final_dermamnist_224.npz'
METADATAPATH = '/content/drive/MyDrive/final_metadata.json'
OUTPUTDIR = '/content/drive/MyDrive/dermamnist/phase2'

# Load metadata
with open(METADATAPATH, 'r') as f:
    metadata = json.load(f)

print("Metadata normalized_class_weights:", metadata['normalized_class_weights'])
print("Keys:", list(metadata['normalized_class_weights'].keys()))

UNIFIED_MEAN = np.array(metadata['unified_stats']['mean'])
UNIFIED_STD = np.array(metadata['unified_stats']['std'])

# Class weights: Original but unweighted for CE baseline
class_weights_dict = metadata['normalized_class_weights']
LOSS_WEIGHTS = torch.tensor([class_weights_dict[str(i)] for i in range(7)]).float()
print(f"Loss Weights (original, unweighted CE for baseline): {LOSS_WEIGHTS}")

# Sampler ablated (no weighted for now)
class_counts = metadata['class_counts']['train']
inverse_freq = [1.0 / class_counts[str(i)] for i in range(7)]
SAMPLER_WEIGHTS = torch.tensor(inverse_freq)

CLASSES = list(range(7))

print(f"Loaded: Unified Mean={UNIFIED_MEAN}, Std={UNIFIED_STD}, Loss Weights shape={LOSS_WEIGHTS.shape}")
print(f"ImageNet Norm ready: Mean={IMAGENET_MEAN}, Std={IMAGENET_STD}")
print(f"Test 1 Config: Full SUBSET_FRACTION={SUBSET_FRACTION}, Batch={BATCH_SIZE} (adjust to 16 in loaders), Unweighted CE (target 88-89% B)")

"""3rd"""

class SkinDataset(Dataset):
    def __init__(self, images, labels, transform=None):
        self.images = images
        self.labels = labels
        self.transform = transform

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        img = self.images[idx].astype(np.uint8)
        if len(img.shape) == 2 or img.shape[2] == 1:
            img = np.repeat(img[..., np.newaxis], 3, axis=-1)
        label = self.labels[idx]

        if self.transform:
            augmented = self.transform(image=img)
            img = augmented['image']
        else:
            img = torch.from_numpy(img.transpose(2, 0, 1)).float() / 255.0

        return img, label

# Moderate augs for A (light; unchanged for 77%)
train_transform = A.Compose([
    A.RandomResizedCrop(size=(224, 224), scale=(0.85, 1.0), p=1.0),
    A.HorizontalFlip(p=0.5),
    A.VerticalFlip(p=0.2),
    A.Rotate(limit=8, p=0.3),
    A.ColorJitter(brightness=0.08, contrast=0.08, saturation=0.08, hue=0.03, p=0.4),
    A.CoarseDropout(max_holes=1, max_height=32, max_width=32, min_height=8, min_width=8, fill_value=0, p=0.1),
    A.Normalize(mean=IMAGENET_MEAN, std=IMAGENET_STD),
    ToTensorV2()
])

# Stronger for B (unchanged; diversity)
train_transform_b = A.Compose([
    A.RandomResizedCrop(size=(224, 224), scale=(0.8, 1.0), p=1.0),
    A.HorizontalFlip(p=0.5),
    A.VerticalFlip(p=0.2),
    A.Rotate(limit=10, p=0.5),
    A.ColorJitter(brightness=0.1, contrast=0.1, saturation=0.1, hue=0.05, p=0.5),
    A.CoarseDropout(max_holes=1, max_height=50, max_width=50, min_height=10, min_width=10, fill_value=0, p=0.2),
    A.Normalize(mean=IMAGENET_MEAN, std=IMAGENET_STD),
    ToTensorV2()
])

val_test_transform = A.Compose([
    A.Resize(224, 224, always_apply=True),
    A.Normalize(mean=IMAGENET_MEAN, std=IMAGENET_STD),
    ToTensorV2()
])

# Test 1: Full Load (~20k train, 512 val; batch=16 for memory)
print("Loading full dataset (SUBSET_FRACTION=1.0)...")
data = np.load(DATAPATH, allow_pickle=True)
train_images = data['train_images'][:int(len(data['train_images']) * SUBSET_FRACTION)]  # Full: all
train_labels = data['train_labels'].flatten()[:len(train_images)]
val_images = data['val_images'][:int(len(data['val_images']) * SUBSET_FRACTION)]  # Full: all ~512
val_labels = data['val_labels'].flatten()[:len(val_images)]
test_images = data['test_images']
test_labels = data['test_labels'].flatten()

print(f"Loaded Full: Train {len(train_images):,}, Val {len(val_images):,}, Test {len(test_images):,}")

unique_train_labels = np.unique(train_labels)
print(f"Unique train labels: {unique_train_labels} (expected: [0 1 2 3 4 5 6])")

train_ds = SkinDataset(train_images, train_labels, train_transform)
val_ds = SkinDataset(val_images, val_labels, val_test_transform)
test_ds = SkinDataset(test_images, test_labels, val_test_transform)

print("Ablating sampler: shuffle=True for natural distribution")

# Test 1: Batch=16 for full (fit GPU; else 32 for subset)
full_batch = 16 if SUBSET_FRACTION == 1.0 else BATCH_SIZE
train_loader = DataLoader(train_ds, batch_size=full_batch, shuffle=True, num_workers=NUM_WORKERS, pin_memory=True)
val_loader = DataLoader(val_ds, batch_size=full_batch, shuffle=False, num_workers=NUM_WORKERS, pin_memory=True)
test_loader = DataLoader(test_ds, batch_size=full_batch, shuffle=False, num_workers=NUM_WORKERS, pin_memory=True)

imgs, lbls = next(iter(train_loader))
print(f"Sample batch (full data, batch={full_batch}): Labels dist {np.bincount(lbls.numpy())}")

print(f"Loaders ready (full data, batch={full_batch}, moderate augs for Test 1 88-89%)")

"""4th"""

import torch
import torch.nn as nn
from torch.amp import GradScaler
from torch.nn import CrossEntropyLoss

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
scaler = GradScaler('cuda')
print(f"Using device: {device}")

# Model: EfficientNet-B0
model = timm.create_model('efficientnet_b0', pretrained=True, num_classes=7)
model = model.to(device)

# Tweak: Mid dropout=0.55 (from 0.6, slight capacity +1%)
model.classifier = nn.Sequential(
    nn.Dropout(0.55),  # Mid reg for 78% (balanced)
    model.classifier
)
print("Head dropout (0.55) for mid reg/capacity (tweak for A 78%).")

# Revert A: Unweighted Smoothed CE (baseline; no weights for major bootstrap)
criterion = CrossEntropyLoss(label_smoothing=LABEL_SMOOTHING)  # 0.07, unweighted
print(f"Criterion for A: Unweighted Smoothed CE (smoothing={LABEL_SMOOTHING}, baseline - majors drive head)")

# Optimizer/scheduler (mid WD=3e-4)
def get_optimizer(model, lr):
    return torch.optim.AdamW(model.parameters(), lr=lr, weight_decay=WEIGHT_DECAY)  # 3e-4

def get_scheduler(optimizer, total_epochs):
    return torch.optim.lr_scheduler.CosineAnnealingWarmRestarts(optimizer, T_0=total_epochs//3, T_mult=2, eta_min=1e-6)

optimizer = get_optimizer(model, LEARNING_RATE_A)  # 4e-3 for A
scheduler = get_scheduler(optimizer, NUM_EPOCHS_STAGE_A)  # 15 epochs

print("Model ready: EfficientNet-B0, dropout 0.55/WD 3e-4 (mid tweak), Unweighted CE for A 78%.")

"""5th"""

import numpy as np
import random
import torch.nn.functional as F

def train_epoch(model, loader, optimizer, criterion, scaler, device, is_train=True, stage='A'):  # Add stage param
    if is_train:
        model.train()
    else:
        model.eval()

    running_loss = 0.0
    all_preds = []
    all_labels_list = []
    all_probs = []

    with tqdm(loader, desc="Epoch" if is_train else "Eval") as pbar:
        for batch_idx, (imgs, labels) in enumerate(pbar):
            imgs, labels = imgs.to(device), labels.to(device)

            # Fix: Cast to long for CE
            hard_labels = labels.long()

            # MixUp: Only for stage='B' and train (disabled for A)
            mixup_applied = False
            if is_train and stage == 'B' and random.random() < 0.5:
                # Define RARE_CLASSES if not global (hardcode for safety)
                RARE_CLASSES = torch.tensor([0, 3, 6], device=device)
                rare_mask = torch.isin(hard_labels, RARE_CLASSES)
                if rare_mask.any():
                    perm = torch.randperm(hard_labels.size(0), device=device)
                    lam = np.random.beta(0.2, 0.2)  # Beta inline
                    lam_tensor = torch.full((hard_labels.size(0),), lam, dtype=torch.float32, device=device)

                    mixed_imgs = lam_tensor.view(-1, 1, 1, 1) * imgs + (1 - lam_tensor.view(-1, 1, 1, 1)) * imgs[perm]
                    imgs = mixed_imgs

                    # Soft for potential, but loss on hard
                    onehot_orig = F.one_hot(hard_labels, num_classes=7).float()
                    onehot_perm = F.one_hot(hard_labels[perm], num_classes=7).float()
                    soft_labels = lam_tensor.view(-1, 1) * onehot_orig + (1 - lam_tensor.view(-1, 1)) * onehot_perm

                    mixup_applied = True
                    if batch_idx < 5:
                        print(f"MixUp applied (B batch {batch_idx}, lam={lam:.3f}, rares={rare_mask.sum().item()}/{hard_labels.size(0)})")

            optimizer.zero_grad() if is_train else None

            with torch.amp.autocast('cuda'):
                outputs = model(imgs)
                loss = criterion(outputs, hard_labels)  # Hard always for unweighted CE

            if is_train:
                scaler.scale(loss).backward()
                scaler.step(optimizer)
                scaler.update()

            running_loss += loss.item() * imgs.size(0)
            probs = torch.softmax(outputs, dim=1)
            _, preds = torch.max(outputs, 1)

            all_preds.extend(preds.cpu().numpy())
            all_labels_list.extend(hard_labels.cpu().numpy())
            all_probs.extend(probs.detach().cpu().numpy())

            if is_train:
                pbar.set_postfix({'loss': f"{loss.item():.4f}"})

    avg_loss = running_loss / len(loader.dataset)
    acc = accuracy_score(all_labels_list, all_preds)
    f1 = f1_score(all_labels_list, all_preds, average='macro', zero_division=0)

    all_probs_arr = np.array(all_probs, dtype=np.float64)
    all_probs_arr = np.clip(all_probs_arr, 0, 1)
    all_probs_arr = all_probs_arr / all_probs_arr.sum(axis=1, keepdims=True)
    all_labels = np.array(all_labels_list)

    try:
        auroc = roc_auc_score(all_labels, all_probs_arr, multi_class='ovr', average='macro')
        if not np.isfinite(auroc):
            auroc = 0.5
    except Exception as e:
        print(f"AUROC warning: {e} - Using 0.5 fallback")
        auroc = 0.5

    return avg_loss, acc, f1, auroc, all_preds, all_labels_list

def log_metrics(epoch, train_results, val_results, log_file):
    with open(log_file, 'a') as f:
        f.write(f"{epoch},{train_results[0]:.4f},{train_results[1]:.4f},{train_results[2]:.4f},{train_results[3]:.4f},"
                f"{val_results[0]:.4f},{val_results[1]:.4f},{val_results[2]:.4f},{val_results[3]:.4f}\n")

log_file = os.path.join(OUTPUT_DIR, 'logs/training_log.csv')
if not os.path.exists(log_file):
    with open(log_file, 'w') as f:
        f.write("epoch,train_loss,train_acc,train_f1,train_auroc,val_loss,val_acc,val_f1,val_auroc\n")

print("Functions ready (stage-aware: MixUp off for A, on for B optional; long() fix).")

"""6th"""

import numpy as np  # For bincount (from Cell 2, but ensure)

# Stage A: Freeze backbone (head only) - Robust for TIMM EfficientNet
for name, param in model.named_parameters():
    if 'classifier' not in name:  # Freeze stem, blocks, conv_head—train only classifier
        param.requires_grad = False

# Verify: Print trainable params (and sample names for debug)
trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
total_params = sum(p.numel() for p in model.parameters())
print(f"Stage A: Trainable params: {trainable_params:,} / {total_params:,} ({100*trainable_params/total_params:.1f}%)")  # ~0.2% (head only)

# Optional debug: Print param names (uncomment first time to verify classifier only)
# print("Trainable params names:")
# for name, param in model.named_parameters():
#     if param.requires_grad:
#         print(f"  {name}: {param.numel()}")

# Ensure scheduler is defined (from Cell 4)
if 'scheduler' not in locals():
    print("Warning: Scheduler not defined—recreate from Cell 4.")
    scheduler = get_scheduler(optimizer, NUM_EPOCHS_STAGE_A)  # Fallback call

best_val_acc_a = 0.0
patience_counter_a = 0
train_losses = []  # Track for convergence debug

print("Starting Stage A: Frozen backbone (head only) - Baseline + mid tweaks for 78%")
for epoch in range(NUM_EPOCHS_STAGE_A):
    train_results = train_epoch(model, train_loader, optimizer, criterion, scaler, device, is_train=True, stage='A')  # Stage 'A': No MixUp, hard labels
    val_results = train_epoch(model, val_loader, optimizer, criterion, scaler, device, is_train=False, stage='A')  # Val no train/mix

    scheduler.step()

    # Log
    global_epoch = epoch + 1
    log_metrics(global_epoch, train_results, val_results, log_file)
    print(f"Epoch {global_epoch}/{NUM_EPOCHS_STAGE_A}: Train Loss {train_results[0]:.4f}, Acc {train_results[1]:.4f}, F1 {train_results[2]:.4f}, AUROC {train_results[3]:.4f} | "
          f"Val Acc {val_results[1]:.4f}, F1 {val_results[2]:.4f}, AUROC {val_results[3]:.4f}")

    # Debug: Acc gap + val preds/labels dist (for imbalance bias check)
    gap = train_results[1] - val_results[1]
    val_preds_dist = np.bincount(val_results[4], minlength=7)  # Preds per class [0-6]
    val_labels_dist = np.bincount(val_results[5], minlength=7)  # True labels per class [0-6]
    print(f"  Acc Gap: {gap:.4f} | Val Preds Dist: {val_preds_dist} | Val Labels Dist: {val_labels_dist}")

    # A-Focused: Track train loss trend (convergence check; expect steady drop)
    train_losses.append(train_results[0])
    if len(train_losses) > 1:
        loss_delta = train_losses[-1] - train_losses[-2]
        print(f"  Train Loss Delta: {loss_delta:.4f} (steady drop target for 78%)")

    # Checkpoint best (A-specific key)
    if val_results[1] > best_val_acc_a:
        best_val_acc_a = val_results[1]
        patience_counter_a = 0
        torch.save({
            'stage': 'A',
            'epoch': global_epoch,
            'model_state_dict': model.state_dict(),
            'optimizer_state_dict': optimizer.state_dict(),
            'val_acc': best_val_acc_a,
        }, os.path.join(OUTPUT_DIR, 'models/best_stageA.pth'))
        print(f"  New best val acc: {best_val_acc_a:.4f} - Stage A checkpoint saved")
    else:
        patience_counter_a += 1
        if patience_counter_a >= PATIENCE:
            print(f"Early stopping in Stage A at epoch {global_epoch}")
            break

print(f"Stage A complete. Best Val Acc: {best_val_acc_a:.4f} (target 78%; if low, tweak LR_A=3.5e-3 in Cell 2)")

"""7th"""

import numpy as np  # For bincount
from sklearn.metrics import f1_score  # For rare F1 (already imported, but ensure)

# Total params (ensure defined; from A)
if 'total_params' not in locals():
    total_params = sum(p.numel() for p in model.parameters())

print("Starting Stage B: Unfreeze (full model), stronger augs/LR_B=5e-5 - Test 1 Full Data (CE no focal)")

# Load best A (77%; if rerun A full, this is new best)
checkpoint_path = os.path.join(OUTPUTDIR, 'models/best_stageA.pth')
if os.path.exists(checkpoint_path):
    checkpoint = torch.load(checkpoint_path, map_location=device)
    model.load_state_dict(checkpoint['model_state_dict'])
    print(f"Loaded best Stage A (epoch {checkpoint['epoch']}, val_acc {checkpoint['val_acc']:.4f})")
    best_val_acc_b = checkpoint['val_acc']
else:
    print("Warning: No A checkpoint—rerun A or use current")
    best_val_acc_b = 0.0

# Unfreeze all
for param in model.parameters():
    param.requires_grad = True
trainable_params_b = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f"Stage B: Trainable params: {trainable_params_b:,} / {total_params:,} (100%)")

# Swap to B augs (stronger)
train_ds.transform = train_transform_b
print("Swapped to train_transform_b for B diversity")

# Test 1: Reload full loaders (batch=16 for memory)
full_batch = 16 if SUBSET_FRACTION == 1.0 else BATCH_SIZE
train_loader = DataLoader(train_ds, batch_size=full_batch, shuffle=True, num_workers=NUM_WORKERS, pin_memory=True)
val_loader = DataLoader(val_ds, batch_size=full_batch, shuffle=False, num_workers=NUM_WORKERS, pin_memory=True)
print(f"Reloaded full loaders (batch={full_batch}, train {len(train_ds):,} samples)")

# New B optimizer/scheduler (conservative LR=5e-5)
optimizer = get_optimizer(model, LEARNING_RATE_B)
scheduler = get_scheduler(optimizer, NUM_EPOCHS_STAGE_B)

# CE same as A (unweighted smoothed; stable)
criterion = CrossEntropyLoss(label_smoothing=LABEL_SMOOTHING)
print(f"B Loss: Unweighted Smoothed CE (smoothing={LABEL_SMOOTHING}, Test 1 full data)")

patience_counter_b = 0
print(f"Starting B from {best_val_acc_b:.4f} (full data target 88-89%)")

prev_train_loss = float('inf')  # For delta
for epoch in range(NUM_EPOCHS_STAGE_B):
    train_results = train_epoch(model, train_loader, optimizer, criterion, scaler, device, is_train=True)
    val_results = train_epoch(model, val_loader, optimizer, criterion, scaler, device, is_train=False)

    scheduler.step()

    global_epoch = NUM_EPOCHS_STAGE_A + epoch + 1
    log_metrics(global_epoch, train_results, val_results, log_file)
    print(f"Stage B Epoch {epoch+1}/{NUM_EPOCHS_STAGE_B} (Global {global_epoch}): Train Loss {train_results[0]:.4f}, Acc {train_results[1]:.4f}, F1 {train_results[2]:.4f}, AUROC {train_results[3]:.4f} | "
          f"Val Acc {val_results[1]:.4f}, F1 {val_results[2]:.4f}, AUROC {val_results[3]:.4f}")

    gap = train_results[1] - val_results[1]
    val_preds_dist = np.bincount(val_results[4], minlength=7)
    val_labels_dist = np.bincount(val_results[5], minlength=7)
    print(f"  Acc Gap: {gap:.4f} | Val Preds Dist: {val_preds_dist} | Val Labels Dist: {val_labels_dist}")

    # Debug: Loss delta + class5 bias
    loss_delta = train_results[0] - prev_train_loss
    class5_bias = (val_preds_dist[5] / val_labels_dist[5] * 100) if val_labels_dist[5] > 0 else 0
    print(f"  Train Loss Delta: {loss_delta:.4f} | Class5 Bias: {class5_bias:.1f}% (target 90-105%)")

    # Test 1: Avg Rare F1 (classes [0,3,6]; target >0.6 for rares boost)
    rare_classes = [0, 3, 6]
    rare_f1 = f1_score(val_results[5], val_results[4], average=None, zero_division=0)[rare_classes].mean()
    print(f"  Avg Rare F1: {rare_f1:.4f} (classes {rare_classes}, target >0.6)")
    prev_train_loss = train_results[0]

    if val_results[1] > best_val_acc_b:
        best_val_acc_b = val_results[1]
        patience_counter_b = 0
        torch.save({
            'stage': 'B',
            'epoch': global_epoch,
            'model_state_dict': model.state_dict(),
            'optimizer_state_dict': optimizer.state_dict(),
            'val_acc': best_val_acc_b,
        }, os.path.join(OUTPUTDIR, 'models/best_overall.pth'))
        print(f"  New best val acc: {best_val_acc_b:.4f} - Overall checkpoint saved")
    else:
        patience_counter_b += 1
        if patience_counter_b >= PATIENCE:
            print(f"Early stopping B at epoch {epoch+1}")
            break

print(f"B complete. Best Val Acc: {best_val_acc_b:.4f} (Test 1 full target 88-89%; if +2%, proceed Test 2)")

"""Test"""

# Cell 8: Load Test Dataset & Evaluate 87% Model (Full Test Metrics)
import numpy as np
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score, classification_report, confusion_matrix
import torch.nn as nn
from tqdm import tqdm
import torch
import matplotlib.pyplot as plt
import seaborn as sns


# Paths & Params (from Cell 2/attached file)
DATAPATH = '/content/drive/MyDrive/final_dermamnist_224.npz'
OUTPUTDIR = '/content/drive/MyDrive/dermamnist/phase2'  # Or '/MyDrivedermamnistphase2' if mismatch
BATCH_SIZE = 16  # Full data safe; NUM_WORKERS=2, LABEL_SMOOTHING=0.07 from Cell 2
IMAGENET_MEAN = np.array([0.485, 0.456, 0.406])
IMAGENET_STD = np.array([0.229, 0.224, 0.225])

# Reload Test Dataset if Missing (from Cell 3/attached; full ~2007 samples)
if 'test_ds' not in locals() or 'test_loader' not in locals():
    print("Reloading test dataset (ensure DATAPATH exists)...")
    from torch.utils.data import DataLoader
    import albumentations as A
    from albumentations.pytorch import ToTensorV2
    from . import SkinDataset  # Assume defined in Cell 3; paste if needed below

    class SkinDataset(torch.utils.data.Dataset):  # If not defined, paste full from attached Cell 3
        def __init__(self, images, labels, transform=None):
            self.images = images
            self.labels = labels
            self.transform = transform

        def __len__(self):
            return len(self.labels)

        def __getitem__(self, idx):
            img = self.images[idx].astype(np.uint8)
            if len(img.shape) == 2 or img.shape[2] == 1:
                img = np.repeat(img[..., np.newaxis], 3, axis=-1)
            label = self.labels[idx]
            if self.transform:
                augmented = self.transform(image=img)
                img = augmented['image']
            else:
                img = torch.from_numpy(img.transpose(2, 0, 1)).float() / 255.0
            return img, label

    val_test_transform = A.Compose([
        A.Resize(224, 224, always_apply=True),
        A.Normalize(mean=IMAGENET_MEAN, std=IMAGENET_STD),
        ToTensorV2()
    ])

    data = np.load(DATAPATH, allow_pickle=True)
    test_images = data['test_images']
    test_labels = data['test_labels'].flatten()  # int32 if cast earlier
    print(f"Test shape: Images {test_images.shape} ({len(test_images):,} samples), Labels unique {np.unique(test_labels)}")

    test_ds = SkinDataset(test_images, test_labels, val_test_transform)
    NUM_WORKERS = 2
    test_loader = DataLoader(test_ds, batch_size=BATCH_SIZE, shuffle=False, num_workers=NUM_WORKERS, pin_memory=True)
    print(f"Test loader ready: {len(test_loader):,} batches, {len(test_ds):,} samples")

# Load Best Model (87.82% Val from Stage B; assume model from Cell 4: timm EfficientNet-B0)
model_path = os.path.join(OUTPUTDIR, 'models/best_overall.pth')  # Or 'best_model.pth' from attached
if os.path.exists(model_path):
    checkpoint = torch.load(model_path, map_location=device)
    model.load_state_dict(checkpoint['model_state_dict'])
    print(f"Loaded 87% model: Epoch {checkpoint['epoch']}, Val Acc {checkpoint['val_acc']:.4f}")
else:
    print(f"Warning: No {model_path}—check Drive/models/. Using current model (may be untrained).")

model.eval()  # Eval mode: dropout=0, BN fixed

# Test Criterion (Smoothed CE for loss; no_grad eval)
criterion_test = nn.CrossEntropyLoss(label_smoothing=LABEL_SMOOTHING)

# Evaluation Function (Adapted from attached file/train_epoch; no_grad, no opt/AMP for test)
def evaluate_model(model, loader, criterion, device):
    model.eval()
    all_preds = []
    all_labels = []
    all_probs = []
    total_loss = 0.0
    num_batches = len(loader)

    with torch.no_grad():  # No gradients for inference
        for batch in tqdm(loader, desc="Test Eval"):
            images, labels = batch
            images, labels = images.to(device), labels.to(device)

            outputs = model(images)
            loss = criterion(outputs, labels)
            total_loss += loss.item()

            probs = torch.softmax(outputs, dim=1)
            preds = torch.argmax(outputs, dim=1)

            all_preds.extend(preds.cpu().numpy())
            all_probs.extend(probs.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())

    all_preds = np.array(all_preds)
    all_labels = np.array(all_labels)
    all_probs = np.array(all_probs)

    # Metrics
    acc = accuracy_score(all_labels, all_preds)
    f1_macro = f1_score(all_labels, all_preds, average='macro', zero_division=0)
    auroc = roc_auc_score(all_labels, all_probs, multi_class='ovr', average='macro')
    avg_loss = total_loss / num_batches

    return avg_loss, acc, f1_macro, auroc, all_preds, all_labels, all_probs

# Run Test Evaluation
print("\nRunning full test evaluation...")
test_loss, test_acc, test_f1, test_auroc, test_preds, test_labels, test_probs = evaluate_model(
    model, test_loader, criterion_test, device
)

# Advanced Metrics (Rare F1, Bias, Report, CM)
rare_classes = [0, 3, 6]
rare_f1 = f1_score(test_labels, test_preds, average=None, zero_division=0)[rare_classes].mean()
test_preds_dist = np.bincount(test_preds, minlength=7)
test_labels_dist = np.bincount(test_labels, minlength=7)
class5_bias = (test_preds_dist[5] / test_labels_dist[5] * 100) if test_labels_dist[5] > 0 else 0

class_report = classification_report(test_labels, test_preds, target_names=[f'Class{i}' for i in range(7)],
                                     output_dict=True, zero_division=0)
cm = confusion_matrix(test_labels, test_preds)

# Output Results
print(f"\n=== Test Metrics (87% Val Model) ===")
print(f"Test Loss: {test_loss:.4f}")
print(f"Test Accuracy: {test_acc:.4f} ({test_acc*100:.2f}%)")
print(f"Test F1 (Macro Avg): {test_f1:.4f}")
print(f"Test AUROC (OvR Macro): {test_auroc:.4f}")
print(f"Avg Rare F1 (Classes {rare_classes}): {rare_f1:.4f} (target >0.70)")
print(f"Preds Dist: {test_preds_dist} | Labels Dist: {test_labels_dist}")
print(f"Class 5 (nv) Bias: {class5_bias:.1f}% (target 90-105%; indicates majority over/under-pred)")

print(f"\n=== Per-Class Details ===")
for i in range(7):
    prec = class_report[f'Class{i}']['precision']
    rec = class_report[f'Class{i}']['recall']
    f1_i = class_report[f'Class{i}']['f1-score']
    support = class_report[f'Class{i}']['support']
    print(f"Class {i} (support {support}): Prec {prec:.3f}, Rec {rec:.3f}, F1 {f1_i:.3f}")

print(f"\n=== Confusion Matrix Summary ===")
print(f"Shape: {cm.shape} | Total Errors: {np.sum(cm) - np.trace(cm)} ({(np.sum(cm) - np.trace(cm))/np.sum(cm)*100:.1f}% misclassified)")
rare_cm_trace = np.trace(cm[np.ix_(rare_classes, rare_classes)])
rare_cm_total = np.sum(cm[np.ix_(rare_classes, rare_classes)])
print(f"Rare Classes Avg Recall: {rare_cm_trace / rare_cm_total:.3f}")

# Optional: Save Results (CSV/JSON for reports)
results_dict = {
    'test_loss': test_loss, 'test_acc': test_acc, 'test_f1': test_f1, 'test_auroc': test_auroc,
    'rare_f1': rare_f1, 'class5_bias': class5_bias, 'preds_dist': test_preds_dist.tolist(),
    'labels_dist': test_labels_dist.tolist(), 'cm': cm.tolist()
}
import json
with open(os.path.join(OUTPUTDIR, 'logs/test_results_87_model.json'), 'w') as f:
    json.dump(results_dict, f, indent=4)
print(f"\nResults saved to {OUTPUTDIR}/logs/test_results_87_model.json")

print("\nTest complete. Expected: Acc ~85-88%, Rare F1 ~0.70-0.75. If low, verify checkpoint/load.")


print(f"\n=== Confusion Matrix Summary ===")
print(f"Shape: {cm.shape} | Total Errors: {np.sum(cm) - np.trace(cm)} ({(np.sum(cm) - np.trace(cm))/np.sum(cm)*100:.1f}% misclassified)")
rare_cm_trace = np.trace(cm[np.ix_(rare_classes, rare_classes)])
rare_cm_total = np.sum(cm[np.ix_(rare_classes, rare_classes)])
print(f"Rare Classes Avg Recall: {rare_cm_trace / rare_cm_total:.3f}")

# Plot confusion matrix heatmap
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=True,
            xticklabels=[f'Class {i}' for i in range(7)],
            yticklabels=[f'Class {i}' for i in range(7)])
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix for EfficientNet-B0 on DermaMNIST Test Set')
plt.tight_layout()
plt.show()

"""8th"""

# Load and plot logs
import pandas as pd
df = pd.read_csv(log_file)

plt.figure(figsize=(12, 4))
plt.subplot(1, 2, 1)
plt.plot(df['epoch'], df['train_acc'], label='Train Acc')
plt.plot(df['epoch'], df['val_acc'], label='Val Acc')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.title('Accuracy Curve')

plt.subplot(1, 2, 2)
plt.plot(df['epoch'], df['train_loss'], label='Train Loss')
plt.plot(df['epoch'], df['val_loss'], label='Val Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.title('Loss Curve')

plt.tight_layout()
plt.savefig(os.path.join(OUTPUT_DIR, 'plots/learning_curves.png'), dpi=300)
plt.show()

print("Curves saved. Download from Drive if needed.")

"""9th"""

# Load best model
model.load_state_dict(torch.load(os.path.join(OUTPUT_DIR, 'models/best_model.pth'))['model_state_dict'])
model.eval()

# TTA transforms (8 variants)
tta_transforms = [
    val_test_transform,  # Original
    A.Compose([A.HorizontalFlip(p=1.0), A.Normalize(mean=UNIFIED_MEAN, std=UNIFIED_STD), ToTensorV2()]),
    A.Compose([A.VerticalFlip(p=1.0), A.Normalize(mean=UNIFIED_MEAN, std=UNIFIED_STD), ToTensorV2()]),
    A.Compose([A.Rotate(limit=10, p=1.0), A.Normalize(mean=UNIFIED_MEAN, std=UNIFIED_STD), ToTensorV2()]),
    # Add more: e.g., Horizontal + Vertical, etc. (up to 8-16 for 1% boost)
]

def tta_predict(model, loader, transforms, device, num_tta=4):  # Use first 4 for demo
    all_logits = []
    with torch.no_grad():
        for imgs, labels in loader:
            imgs_orig = imgs.to(device)
            batch_logits = torch.zeros(imgs.size(0), 7, device=device)

            for tta_idx, tform in enumerate(transforms[:num_tta]):
                if tta_idx == 0:
                    with autocast():
                        logits = model(imgs_orig)
                else:
                    augmented_imgs = []
                    for img in imgs:
                        aug_img = np.array(Image.fromarray((img.cpu().numpy().transpose(1,2,0) * 255).astype(np.uint8)))
                        aug = tform(image=aug_img)
                        augmented_imgs.append(aug['image'])
                    aug_batch = torch.stack(augmented_imgs).to(device)
                    with autocast():
                        logits = model(aug_batch)

                batch_logits += logits / num_tta

            all_logits.append(batch_logits)

    all_logits = torch.cat(all_logits)
    probs = torch.softmax(all_logits, dim=1)
    preds = torch.argmax(probs, dim=1).cpu().numpy()
    return preds, probs.cpu().numpy()

tta_preds, tta_probs = tta_predict(model, test_loader, tta_transforms, device)

tta_acc = accuracy_score(test_labels, tta_preds)
tta_f1 = f1_score(test_labels, tta_preds, average='macro')
tta_auroc = roc_auc_score(test_labels, tta_probs, multi_class='ovr', average='macro')

print(f"TTA Results: Acc {tta_acc:.4f}, F1 {tta_f1:.4f}, AUROC {tta_auroc:.4f}")

# Save TTA eval
with open(os.path.join(OUTPUT_DIR, 'logs/tta_results.txt'), 'w') as f:
    f.write(f"Acc: {tta_acc}, F1: {tta_f1}, AUROC: {tta_auroc}\n")

"""10th"""

# Light Ensembling: Train 2 additional models (seeds 123, 456) from base (seed 42 already trained)
# ~1 hour total—run if needed for 1% boost. Averages predictions for final ensemble.

ENSEMBLE_SEEDS = [123, 456]  # Base is seed 42
NUM_ENS_EPOCHS = 5  # Quick fine-tune per model (increase to 10 for better, +30 mins)
ensemble_states = {}  # Dict of {seed: state_dict}
ensemble_preds = []   # List of preds per model for averaging
ensemble_probs_list = []  # For logit averaging
ensemble_log = os.path.join(OUTPUT_DIR, 'logs/ensemble_log.csv')

if not os.path.exists(ensemble_log):
    with open(ensemble_log, 'w') as f:
        f.write("seed,acc,f1,auroc\n")

# Base model state (from best_model.pth or current model)
base_model_state = torch.load(os.path.join(OUTPUT_DIR, 'models/best_model.pth'))['model_state_dict']

# Ensure evaluate function is available (copy from Cell 11 if not run)
def evaluate(model, loader, device):
    model.eval()
    all_preds = []
    all_labels_list = []
    all_probs = []

    with torch.no_grad():
        for imgs, labels in tqdm(loader, desc="Evaluating"):
            imgs, labels = imgs.to(device), labels.to(device)
            with autocast():
                outputs = model(imgs)
            probs = torch.softmax(outputs, dim=1)
            preds = torch.argmax(probs, dim=1)

            all_preds.extend(preds.cpu().numpy())
            all_probs.extend(probs.cpu().numpy())
            all_labels_list.extend(labels.cpu().numpy())

    acc = accuracy_score(all_labels_list, all_preds)
    f1 = f1_score(all_labels_list, all_preds, average='macro')
    auroc = roc_auc_score(all_labels_list, all_probs, multi_class='ovr', average='macro')

    return acc, f1, auroc, all_preds, all_probs  # Return preds/probs for ensemble avg

print("Starting ensemble training...")
for seed in ENSEMBLE_SEEDS:
    print(f"\n--- Ensemble Member: Seed {seed} ---")
    set_seed(seed)

    # Create new model, warm-start from base
    ens_model = timm.create_model('efficientnet_b0', pretrained=True, num_classes=7).to(device)
    ens_model.load_state_dict(base_model_state)
    ens_optimizer = get_optimizer(ens_model, LEARNING_RATE_B)
    ens_scheduler = get_scheduler(ens_optimizer, NUM_ENS_EPOCHS)

    # Quick fine-tune: NUM_ENS_EPOCHS epochs
    best_ens_val_acc = 0.0
    for e in range(NUM_ENS_EPOCHS):
        train_res = train_epoch(ens_model, train_loader, ens_optimizer, criterion, scaler, device, True)
        val_res = train_epoch(ens_model, val_loader, ens_optimizer, criterion, scaler, device, False)
        ens_scheduler.step()

        print(f"Ens Epoch {e+1}/{NUM_ENS_EPOCHS}: Train Acc {train_res[1]:.4f} | Val Acc {val_res[1]:.4f}")

        # Save best per member
        if val_res[1] > best_ens_val_acc:
            best_ens_val_acc = val_res[1]
            torch.save(ens_model.state_dict(), os.path.join(OUTPUT_DIR, f'models/ensemble_best_seed_{seed}.pth'))

    # Evaluate on test
    ens_acc, ens_f1, ens_auroc, ens_preds, ens_probs = evaluate(ens_model, test_loader, device)

    # Log per-member
    with open(ensemble_log, 'a') as f:
        f.write(f"{seed},{ens_acc:.4f},{ens_f1:.4f},{ens_auroc:.4f}\n")

    print(f"Seed {seed} Test: Acc {ens_acc:.4f}, F1 {ens_f1:.4f}, AUROC {ens_auroc:.4f}")

    # Store for averaging
    ensemble_states[seed] = ens_model.state_dict()
    ensemble_preds.append(ens_preds)
    ensemble_probs_list.append(np.array(ens_probs))

    torch.save(ensemble_states[seed], os.path.join(OUTPUT_DIR, f'models/ensemble_seed_{seed}.pth'))

# Base model preds (seed 42)
base_acc, base_f1, base_auroc, base_preds, base_probs = evaluate(model, test_loader, device)  # Re-eval base if needed
ensemble_preds.insert(0, base_preds)  # Include base as first
ensemble_probs_list.insert(0, np.array(base_probs))

# Ensemble averaging: Average probabilities across models
num_models = len(ENSEMBLE_SEEDS) + 1  # Base + added
avg_probs = np.mean(ensemble_probs_list, axis=0)
ensemble_final_preds = np.argmax(avg_probs, axis=1)

# Ensemble metrics
ensemble_final_acc = accuracy_score(test_labels, ensemble_final_preds)
ensemble_final_f1 = f1_score(test_labels, ensemble_final_preds, average='macro')
ensemble_final_auroc = roc_auc_score(test_labels, avg_probs, multi_class='ovr', average='macro')

print(f"\n--- Ensemble Results (Avg across {num_models} models) ---")
print(f"Acc {ensemble_final_acc:.4f}, Macro F1 {ensemble_final_f1:.4f}, Macro AUROC {ensemble_final_auroc:.4f}")

# Save ensemble log (add final row)
with open(ensemble_log, 'a') as f:
    f.write(f"ensemble,{ensemble_final_acc:.4f},{ensemble_final_f1:.4f},{ensemble_final_auroc:.4f}\n")

# Save averaged probs/preds for further use (e.g., XAI)
np.save(os.path.join(OUTPUT_DIR, 'logs/ensemble_avg_probs.npy'), avg_probs)
np.save(os.path.join(OUTPUT_DIR, 'logs/ensemble_final_preds.npy'), ensemble_final_preds)

print("Ensemble complete and saved. Use ensemble_final_preds for final submission/metrics.")

"""11th"""

# Load best model for eval
model.load_state_dict(torch.load(os.path.join(OUTPUT_DIR, 'models/best_model.pth'))['model_state_dict'])
model.eval()

def evaluate(model, loader, device, is_tta=False):
    all_preds = []
    all_labels_list = []
    all_probs = []

    with torch.no_grad():
        for imgs, labels in tqdm(loader, desc="Evaluating"):
            imgs, labels = imgs.to(device), labels.to(device)
            with autocast():
                outputs = model(imgs)
            probs = torch.softmax(outputs, dim=1)
            preds = torch.argmax(probs, dim=1)

            all_preds.extend(preds.cpu().numpy())
            all_probs.extend(probs.cpu().numpy())
            all_labels_list.extend(labels.cpu().numpy())

    acc = accuracy_score(all_labels_list, all_preds)
    f1 = f1_score(all_labels_list, all_preds, average='macro')
    auroc = roc_auc_score(all_labels_list, all_probs, multi_class='ovr', average='macro')

    # Per-class
    per_class_f1 = f1_score(all_labels_list, all_preds, average=None)

    # Confusion matrix
    cm = confusion_matrix(all_labels_list, all_preds)
    plt.figure(figsize=(8,6))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
    plt.xlabel('Predicted')
    plt.ylabel('True')
    plt.title('Confusion Matrix')
    plt.savefig(os.path.join(OUTPUT_DIR, 'plots/confusion_matrix.png'), dpi=300)
    plt.show()

    # Bootstrap CI for acc (1000 resamples)
    bootstraps = []
    for _ in range(1000):
        boot_labels, boot_preds = resample(all_labels_list, all_preds)
        boot_acc = accuracy_score(boot_labels, boot_preds)
        bootstraps.append(boot_acc)
    ci_low, ci_high = np.percentile(bootstraps, [2.5, 97.5])

    return acc, f1, auroc, per_class_f1, cm, (ci_low, ci_high)

# Run eval
acc, f1, auroc, per_class_f1, cm, ci = evaluate(model, test_loader, device)

print(f"Test Results: Acc {acc:.4f} (95% CI: {ci[0]:.4f}-{ci[1]:.4f}), Macro F1 {f1:.4f}, Macro AUROC {auroc:.4f}")
print("Per-class F1:", dict(zip(CLASSES, per_class_f1)))

# Save results
results_file = os.path.join(OUTPUT_DIR, 'logs/evaluation_results.csv')
with open(results_file, 'w') as f:
    f.write("metric,value\n")
    f.write(f"acc,{acc}\n")
    f.write(f"f1,{f1}\n")
    f.write(f"auroc,{auroc}\n")
    for cls, pf1 in zip(CLASSES, per_class_f1):
        f.write(f"f1_class_{cls},{pf1}\n")

print(f"Results saved to {results_file}. Confusion plot in plots/")

# Ablations: Run with flags (e.g., no_weights=True, disable_augs=True)
# For example: To ablate weights, recreate criterion=nn.CrossEntropyLoss()
# Rerun eval and log to ablation CSV (manual for now, or wrap in function)

from google.colab import files

# Download key files
files.download(log_file)
files.download(os.path.join(OUTPUT_DIR, 'models/best_model.pth'))
files.download(os.path.join(OUTPUT_DIR, 'plots/confusion_matrix.png'))
files.download(results_file)

print("Key outputs downloaded. Full folder in Drive: /dermamnist/phase2/")