# -*- coding: utf-8 -*-
"""DWDM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rtLCShlNiHRB_GJ77cwM_49KJJDSmnJz
"""

# Cell 1: Install Dependencies
!pip install timm albumentations ttach

import numpy as np
import os
import torch
from google.colab import drive

# 1. Mount Drive
drive.mount('/content/drive')

# === CONFIGURATION ===
# UPDATE THIS PATH to exactly where you uploaded the file in your Drive
FILE_PATH = '/content/drive/MyDrive/tissue_64_enhanced.npz'

# 2. Check & Load
if not os.path.exists(FILE_PATH):
    print(f"❌ ERROR: File not found at {FILE_PATH}")
    print("Please check the path. Did you upload it to a specific folder?")
else:
    print(f"✅ File found! Loading...")
    data = np.load(FILE_PATH)

    # Inspect contents
    print("\n--- Dataset Info ---")
    print(f"Train Images: {data['train_images'].shape}")
    print(f"Val Images:   {data['val_images'].shape}")
    print(f"Test Images:  {data['test_images'].shape}")

    # Load Metadata (Robust loading)
    # The file stores mean/std as arrays, we extract them for the loader
    mean_val = data['unified_mean'][0] if data['unified_mean'].ndim > 0 else data['unified_mean']
    std_val  = data['unified_std'][0]  if data['unified_std'].ndim > 0 else data['unified_std']

    # Check weights
    if 'class_weights' in data:
        weights = data['class_weights']
        print(f"Class Weights Loaded: {weights}")
    else:
        print("⚠️ Warning: Class weights not found. Will calculate manually if needed.")
        weights = None

    print(f"\nGlobal Mean: {mean_val:.4f}")
    print(f"Global Std:  {std_val:.4f}")

    # Store constants for the next cell
    GLOBAL_MEAN = [mean_val] * 3
    GLOBAL_STD  = [std_val] * 3
    CLASS_WEIGHTS = torch.tensor(weights, dtype=torch.float32) if weights is not None else None

from google.colab import drive
import os

# 1. Force Mount Drive
drive.mount('/content/drive', force_remount=True)

# 2. Create the missing directory
save_dir = '/content/drive/MyDrive/outputs_tissue'
if not os.path.exists(save_dir):
    os.makedirs(save_dir, exist_ok=True)
    print(f"✅ Created missing directory: {save_dir}")
else:
    print(f"✅ Directory exists: {save_dir}")

# 3. Verify path is writable
SAVE_PATH = os.path.join(save_dir, 'best_tissue_model.pth')
print(f"Model will be saved to: {SAVE_PATH}")

import torch
import torch.nn as nn
import timm
import albumentations as A
import numpy as np
import os
from datetime import datetime
from albumentations.pytorch import ToTensorV2
from torch.utils.data import DataLoader, Dataset
from tqdm.notebook import tqdm
from sklearn.metrics import accuracy_score, f1_score
from google.colab import drive

# === 1. SETUP & CONFIGURATION ===
drive.mount('/content/drive', force_remount=True)

# Generate a Unique Run ID (Timestamp) to prevent overwriting previous runs
RUN_ID = datetime.now().strftime("%Y%m%d_%H%M")
SAVE_DIR = '/content/drive/MyDrive/outputs_tissue'
XYZ = '/content/drive/MyDrive'
FILE_PATH = os.path.join(XYZ, 'tissue_64_enhanced.npz')

# Config
BATCH_SIZE = 128
NUM_EPOCHS = 30
LEARNING_RATE = 2e-4
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

if not os.path.exists(SAVE_DIR):
    os.makedirs(SAVE_DIR, exist_ok=True)

print(f"✅ Training on: {DEVICE}")
print(f"🆔 Run ID: {RUN_ID} (Models will be saved with this tag)")

# === 2. ROBUST DATA LOADING ===
print(f"Loading data from {FILE_PATH}...")
with np.load(FILE_PATH) as data:
    train_images = data['train_images']
    train_labels = data['train_labels']
    val_images   = data['val_images']
    val_labels   = data['val_labels']

    try:
        GLOBAL_MEAN = data['unified_mean'].tolist()
        GLOBAL_STD  = data['unified_std'].tolist()
        if not isinstance(GLOBAL_MEAN, list): GLOBAL_MEAN = [GLOBAL_MEAN] * 3
        if not isinstance(GLOBAL_STD, list): GLOBAL_STD = [GLOBAL_STD] * 3
    except:
        print("⚠️ Metadata missing, using defaults.")
        GLOBAL_MEAN = [0.2112, 0.2112, 0.2112]
        GLOBAL_STD  = [0.1591, 0.1591, 0.1591]

    if 'class_weights' in data:
        CLASS_WEIGHTS = torch.tensor(data['class_weights'], dtype=torch.float32).to(DEVICE)
    else:
        CLASS_WEIGHTS = None

# === 3. DATASET CLASS ===
class TissueDataset(Dataset):
    def __init__(self, images, labels, transform=None):
        self.images = images
        self.labels = labels.flatten()
        self.transform = transform

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        img = self.images[idx]
        if img.ndim == 2:
            img = np.stack([img] * 3, axis=-1)
        if self.transform:
            augmented = self.transform(image=img)
            img = augmented['image']
        return img, torch.tensor(self.labels[idx], dtype=torch.long)

# === 4. AUGMENTATIONS & LOADERS ===
train_aug = A.Compose([
    A.Rotate(limit=90, p=0.5),
    A.HorizontalFlip(p=0.5),
    A.VerticalFlip(p=0.5),
    A.CoarseDropout(num_holes_range=(1, 4), hole_height_range=(4, 8), hole_width_range=(4, 8), p=0.2),
    A.Normalize(mean=GLOBAL_MEAN, std=GLOBAL_STD),
    ToTensorV2()
])

val_aug = A.Compose([
    A.Normalize(mean=GLOBAL_MEAN, std=GLOBAL_STD),
    ToTensorV2()
])

train_loader = DataLoader(
    TissueDataset(train_images, train_labels, transform=train_aug),
    batch_size=BATCH_SIZE, shuffle=True, num_workers=2, pin_memory=True
)

val_loader = DataLoader(
    TissueDataset(val_images, val_labels, transform=val_aug),
    batch_size=BATCH_SIZE, shuffle=False, num_workers=2
)

# === 5. MODEL SETUP ===
model = timm.create_model(
    'convnextv2_tiny.fcmae_ft_in1k',
    pretrained=True,
    num_classes=8,
    drop_path_rate=0.2
).to(DEVICE)

criterion = nn.CrossEntropyLoss(weight=CLASS_WEIGHTS, label_smoothing=0.1)
optimizer = torch.optim.AdamW(model.parameters(), lr=LEARNING_RATE, weight_decay=0.05)
scheduler = torch.optim.lr_scheduler.CosineAnnealingWarmRestarts(optimizer, T_0=10, T_mult=2)
amp_device = 'cuda' if torch.cuda.is_available() else 'cpu'
scaler = torch.amp.GradScaler(device=amp_device)

# === 6. TRAINING LOOP ===
best_f1 = 0.0
last_saved_path = None # Keeps track of the file saved IN THIS RUN

print(f"\n🚀 Starting Training Run [{RUN_ID}]...")

for epoch in range(NUM_EPOCHS):
    # --- TRAIN ---
    model.train()
    train_loss = 0

    for images, labels in tqdm(train_loader, desc=f"Epoch {epoch+1}/{NUM_EPOCHS}", leave=False):
        images, labels = images.to(DEVICE), labels.to(DEVICE)

        with torch.amp.autocast(device_type=amp_device, dtype=torch.float16):
            outputs = model(images)
            loss = criterion(outputs, labels)

        optimizer.zero_grad()
        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()

        train_loss += loss.item()

    scheduler.step()

    # --- VALIDATE ---
    model.eval()
    val_preds = []
    val_targets = []

    with torch.no_grad():
        for images, labels in val_loader:
            images, labels = images.to(DEVICE), labels.to(DEVICE)
            with torch.amp.autocast(device_type=amp_device, dtype=torch.float16):
                outputs = model(images)
            preds = torch.argmax(outputs, dim=1)
            val_preds.extend(preds.cpu().numpy())
            val_targets.extend(labels.cpu().numpy())

    val_acc = accuracy_score(val_targets, val_preds)
    val_f1 = f1_score(val_targets, val_preds, average='macro')

    print(f"Epoch {epoch+1} | Loss: {train_loss/len(train_loader):.4f} | Val Acc: {val_acc:.4f} | Val F1: {val_f1:.4f}")

    # === 7. INTELLIGENT SAVING ===
    if val_f1 > best_f1:
        best_f1 = val_f1

        # Construct filename with Run ID and Metrics
        filename = f"tissue_model_{RUN_ID}_acc{val_acc:.4f}_f1{val_f1:.4f}.pth"
        save_path = os.path.join(SAVE_DIR, filename)

        # Save new best model
        torch.save(model.state_dict(), save_path)
        print(f"--> ⭐ New Best Found! Saved: {filename}")

        # Optional: Delete the previous best *of this run* to save space
        # (Passes 'if' only if we saved a file previously in this run loop)
        if last_saved_path and os.path.exists(last_saved_path):
            try:
                os.remove(last_saved_path)
                print(f"    (Removed previous best of this run: {os.path.basename(last_saved_path)})")
            except OSError:
                pass

        last_saved_path = save_path

print("\n✅ Training Complete.")

import torch
import torch.nn as nn
import timm
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score, confusion_matrix, classification_report
from torch.utils.data import DataLoader, Dataset
from albumentations.pytorch import ToTensorV2
import albumentations as A
from tqdm.notebook import tqdm
import os
import glob

# === CONFIGURATION ===
# Automatically find the best model from the last run ID "20260203_1345"
# Or paste the specific path if you know it
SAVE_DIR = '/content/drive/MyDrive/outputs_tissue'
SEARCH_PATTERN = os.path.join(SAVE_DIR, "tissue_model_20260203_1345*.pth")
XYZ = '/content/drive/MyDrive'

# Find the file
list_of_files = glob.glob(SEARCH_PATTERN)
if list_of_files:
    BEST_MODEL_PATH = max(list_of_files, key=os.path.getctime) # Pick the latest one
    print(f"✅ Loading Best Model: {os.path.basename(BEST_MODEL_PATH)}")
else:
    raise FileNotFoundError("Could not find a model file! Check the path.")

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
BATCH_SIZE = 128
NUM_CLASSES = 8
CLASSES = [
    'Kidney Cortex', 'Kidney Medulla', 'Kidney Pelvis',
    'Lung Adeno', 'Lung Squamous', 'Pancreas Ductal',
    'Pancreas Neuro', 'Pancreas Solid'
]

# === 1. LOAD DATA (Test Split Only) ===
FILE_PATH = os.path.join(XYZ, 'tissue_64_enhanced.npz')

print("Loading Test Data...")
with np.load(FILE_PATH) as data:
    test_images = data['test_images']
    test_labels = data['test_labels'].flatten()

    # Load Stats for consistency
    try:
        GLOBAL_MEAN = data['unified_mean'].tolist()
        GLOBAL_STD  = data['unified_std'].tolist()
        if not isinstance(GLOBAL_MEAN, list): GLOBAL_MEAN = [GLOBAL_MEAN] * 3
        if not isinstance(GLOBAL_STD, list): GLOBAL_STD = [GLOBAL_STD] * 3
    except:
        GLOBAL_MEAN = [0.2112, 0.2112, 0.2112]
        GLOBAL_STD  = [0.1591, 0.1591, 0.1591]

# === 2. DATASET & LOADER ===
class TissueDataset(Dataset):
    def __init__(self, images, labels, transform=None):
        self.images = images
        self.labels = labels
        self.transform = transform

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        img = self.images[idx]
        if img.ndim == 2: img = np.stack([img] * 3, axis=-1)
        if self.transform:
            augmented = self.transform(image=img)
            img = augmented['image']
        return img, torch.tensor(self.labels[idx], dtype=torch.long)

test_aug = A.Compose([
    A.Normalize(mean=GLOBAL_MEAN, std=GLOBAL_STD),
    ToTensorV2()
])

test_loader = DataLoader(
    TissueDataset(test_images, test_labels, transform=test_aug),
    batch_size=BATCH_SIZE, shuffle=False, num_workers=2
)

# === 3. MODEL SETUP ===
model = timm.create_model(
    'convnextv2_tiny.fcmae_ft_in1k',
    pretrained=False, # No need to download weights, we load ours
    num_classes=NUM_CLASSES
).to(DEVICE)

# Load State Dict
model.load_state_dict(torch.load(BEST_MODEL_PATH, map_location=DEVICE))
model.eval()

# === 4. INFERENCE LOOP ===
all_preds = []
all_probs = [] # For AUROC
all_targets = []

print("Running Inference on Test Set...")
with torch.no_grad():
    for images, labels in tqdm(test_loader):
        images = images.to(DEVICE)

        # Forward pass
        outputs = model(images)

        # Get Probabilities (Softmax)
        probs = torch.softmax(outputs, dim=1)

        # Get Predictions
        preds = torch.argmax(outputs, dim=1)

        all_probs.extend(probs.cpu().numpy())
        all_preds.extend(preds.cpu().numpy())
        all_targets.extend(labels.numpy())

# Convert to arrays
all_probs = np.array(all_probs)
all_preds = np.array(all_preds)
all_targets = np.array(all_targets)

# === 5. CALCULATE METRICS ===
acc = accuracy_score(all_targets, all_preds)
f1 = f1_score(all_targets, all_preds, average='macro')

# AUROC (One-vs-Rest)
try:
    auroc = roc_auc_score(all_targets, all_probs, multi_class='ovr', average='macro')
except:
    auroc = 0.0
    print("Warning: AUROC calculation failed (possibly missing classes in batch)")

print(f"\n========================================")
print(f"🏆 FINAL TEST RESULTS")
print(f"========================================")
print(f"✅ Accuracy:  {acc*100:.2f}%")
print(f"✅ Macro F1:  {f1:.4f}")
print(f"✅ AUC ROC:   {auroc:.4f}")
print(f"========================================\n")

# === 6. CONFUSION MATRIX HEATMAP ===
cm = confusion_matrix(all_targets, all_preds)
plt.figure(figsize=(10, 8))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=CLASSES, yticklabels=CLASSES)
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title(f'Confusion Matrix (Acc: {acc:.4f})')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

# === 7. CLASSIFICATION REPORT ===
print("\nDetailed Report:")
print(classification_report(all_targets, all_preds, target_names=CLASSES, digits=4))

import matplotlib.pyplot as plt
import numpy as np

# === 1. DATA FROM YOUR LOGS (Hardcoded for your run [20260203_1345]) ===
epochs = list(range(1, 31))

train_losses = [
    1.6228, 1.4772, 1.4257, 1.3893, 1.3535, 1.3209, 1.2896, 1.2589, 1.2366, 1.2203,
    1.3251, 1.3215, 1.3107, 1.2963, 1.2799, 1.2633, 1.2440, 1.2241, 1.1978, 1.1744,
    1.1467, 1.1236, 1.0999, 1.0735, 1.0533, 1.0358, 1.0228, 1.0093, 1.0030, 0.9977
]

val_accs = [
    0.6269, 0.6579, 0.6547, 0.6766, 0.6670, 0.6785, 0.7113, 0.7065, 0.7258, 0.7229,
    0.6967, 0.7102, 0.7072, 0.7236, 0.6943, 0.7077, 0.7308, 0.7036, 0.7159, 0.7070,
    0.7268, 0.7273, 0.7322, 0.7317, 0.7358, 0.7399, 0.7412, 0.7407, 0.7432, 0.7440
]

val_f1s = [
    0.5631, 0.5962, 0.5902, 0.6199, 0.6167, 0.6301, 0.6558, 0.6533, 0.6687, 0.6673,
    0.6334, 0.6487, 0.6483, 0.6557, 0.6392, 0.6458, 0.6642, 0.6458, 0.6561, 0.6520,
    0.6591, 0.6620, 0.6678, 0.6662, 0.6708, 0.6723, 0.6741, 0.6731, 0.6742, 0.6749
]

# === 2. PLOTTING ===
plt.figure(figsize=(15, 6))

# Plot 1: Training Loss
plt.subplot(1, 2, 1)
plt.plot(epochs, train_losses, 'b-o', label='Training Loss', markersize=4)
plt.title('Training Loss vs Epochs')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.grid(True, alpha=0.3)
plt.legend()

# Plot 2: Validation Metrics
plt.subplot(1, 2, 2)
plt.plot(epochs, val_accs, 'g-s', label='Val Accuracy', markersize=4)
plt.plot(epochs, val_f1s, 'm-^', label='Val F1 Score', markersize=4)
plt.title('Validation Performance vs Epochs')
plt.xlabel('Epochs')
plt.ylabel('Score')
plt.ylim(0.5, 0.8) # Zoom in on the relevant range
plt.grid(True, alpha=0.3)
plt.legend()

plt.tight_layout()
plt.show()

from google.colab import drive
import os

# 1. Force the authorization popup
print("🔌 Mounting Google Drive...")
drive.mount('/content/drive', force_remount=True)

# 2. Verify the file actually exists where we think it is
file_path = '/content/drive/MyDrive/tissue_64_enhanced.npz'

if os.path.exists(file_path):
    print(f"\n✅ SUCCESS: File found at {file_path}")
    print("You can now run the next code block.")
else:
    print(f"\n❌ ERROR: File NOT found at {file_path}")
    print("Listing files in 'MyDrive' to help you check the name:")
    # List first 10 files in MyDrive to help debug
    try:
        files = os.listdir('/content/drive/MyDrive')
        print(files[:10])
    except:
        print("Could not list files.")

import torch
import timm
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import albumentations as A
import os
import glob
from albumentations.pytorch import ToTensorV2
from torch.utils.data import DataLoader, Dataset
from tqdm.notebook import tqdm
from sklearn.metrics import confusion_matrix, roc_curve, auc
from sklearn.preprocessing import label_binarize
from itertools import cycle

# ==========================================
# 1. SETUP & REGENERATE PREDICTIONS
# ==========================================
print("🔄 Regenerating predictions... (This takes about 30 seconds)")

# Config
XYZ = '/content/drive/MyDrive'
SAVE_DIR = '/content/drive/MyDrive/outputs_tissue'
FILE_PATH = os.path.join(XYZ, 'tissue_64_enhanced.npz')
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
BATCH_SIZE = 128
CLASSES = [
    'Kidney Cortex', 'Kidney Medulla', 'Kidney Pelvis',
    'Lung Adeno', 'Lung Squamous', 'Pancreas Ductal',
    'Pancreas Neuro', 'Pancreas Solid'
]

# Load Data
with np.load(FILE_PATH) as data:
    test_images = data['test_images']
    test_labels = data['test_labels'].flatten()
    # Use defaults if metadata missing
    GLOBAL_MEAN = [0.2112, 0.2112, 0.2112]
    GLOBAL_STD  = [0.1591, 0.1591, 0.1591]

# Dataset Class
class TissueDataset(Dataset):
    def __init__(self, images, labels, transform=None):
        self.images = images
        self.labels = labels
        self.transform = transform
    def __len__(self): return len(self.labels)
    def __getitem__(self, idx):
        img = self.images[idx]
        if img.ndim == 2: img = np.stack([img] * 3, axis=-1)
        if self.transform: img = self.transform(image=img)['image']
        return img, torch.tensor(self.labels[idx], dtype=torch.long)

# Loader
test_aug = A.Compose([A.Normalize(mean=GLOBAL_MEAN, std=GLOBAL_STD), ToTensorV2()])
test_loader = DataLoader(TissueDataset(test_images, test_labels, transform=test_aug),
                         batch_size=BATCH_SIZE, shuffle=False, num_workers=2)

# Load Best Model
# We look for the specific run ID you mentioned: 20260203_1345
search_pattern = os.path.join(SAVE_DIR, "tissue_model_20260203_1345*.pth")
list_of_files = glob.glob(search_pattern)
if not list_of_files:
    # Fallback: find *any* best model if specific ID not found
    search_pattern = os.path.join(SAVE_DIR, "tissue_model_*.pth")
    list_of_files = glob.glob(search_pattern)

if list_of_files:
    best_model_path = max(list_of_files, key=os.path.getctime)
    print(f"✅ Loading Model: {os.path.basename(best_model_path)}")
else:
    raise FileNotFoundError("❌ No model found! Please check your Drive folder.")

model = timm.create_model('convnextv2_tiny.fcmae_ft_in1k', pretrained=False, num_classes=8).to(DEVICE)
model.load_state_dict(torch.load(best_model_path, map_location=DEVICE))
model.eval()

# Run Inference
all_preds, all_targets, all_probs = [], [], []
with torch.no_grad():
    for images, labels in tqdm(test_loader, desc="Inference"):
        images = images.to(DEVICE)
        outputs = model(images)
        probs = torch.softmax(outputs, dim=1)
        preds = torch.argmax(outputs, dim=1)
        all_probs.extend(probs.cpu().numpy())
        all_preds.extend(preds.cpu().numpy())
        all_targets.extend(labels.numpy())

all_preds = np.array(all_preds)
all_targets = np.array(all_targets)
all_probs = np.array(all_probs)

print("✅ Predictions regenerated! Now plotting...")

# ==========================================
# 2. PLOT GRAPHS
# ==========================================

# --- Graph 1: Confusion Matrix ---
cm_norm = confusion_matrix(all_targets, all_preds, normalize='true')
plt.figure(figsize=(10, 8))
sns.heatmap(cm_norm, annot=True, fmt='.1%', cmap='Blues',
            xticklabels=CLASSES, yticklabels=CLASSES, cbar=False)
plt.title('Normalized Confusion Matrix (Recall %)')
plt.ylabel('True Label')
plt.xlabel('Predicted Label')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

# --- Graph 2: ROC Curves ---
y_test_bin = label_binarize(all_targets, classes=range(len(CLASSES)))
n_classes = y_test_bin.shape[1]
fpr, tpr, roc_auc = dict(), dict(), dict()

for i in range(n_classes):
    fpr[i], tpr[i], _ = roc_curve(y_test_bin[:, i], all_probs[:, i])
    roc_auc[i] = auc(fpr[i], tpr[i])

plt.figure(figsize=(10, 8))
colors = cycle(['navy', 'turquoise', 'darkorange', 'cornflowerblue', 'teal', 'crimson', 'purple', 'green'])
for i, color in zip(range(n_classes), colors):
    plt.plot(fpr[i], tpr[i], color=color, lw=2, label=f'{CLASSES[i]} (AUC = {roc_auc[i]:.2f})')

plt.plot([0, 1], [0, 1], 'k--', lw=2)
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Multi-Class ROC Curves')
plt.legend(loc="lower right")
plt.grid(alpha=0.3)
plt.show()

